### ISSUE TITLE
 JSOUP connect throws error "Too many redirects"

### ISSUE THREAD

**Issue by dexterslaboratory** [jhy/jsoup#1498]
**For url:**
[https://www.thelancet.com/journals/eclinm/article/PIIS2589-5370(21)00062-6/fulltext](https://www.thelancet.com/journals/eclinm/article/PIIS2589-5370(21)00062-6/fulltext )

**Jsoup throws below error:**
java.io.IOException: Too many redirects occurred trying to load URL https://secure.jbs.elsevierhealth.com/action/consumeSsoCookie?redirectUri=https%3A%2F%2Fwww.thelancet.com%2Faction%2FconsumeSharedSessionAction%3FSERVER%3DWZ6myaEXBLHNN%252BUWpfIEYQ%253D%253D%26MAID%3DBeLbtz9y8rWAzuGD%252F%252FTyag%253D%253D%26JSESSIONID%3Daaae9-4koBn-Ad5oqulGx%26ORIGIN%3D213045470%26RD%3DRD&code=null&acw=Secure;SameSite=None&utt=

I've tried version **1.9.2** and **1.13.1** both have the same issue. 

This is probably the same issue as https://github.com/jhy/jsoup/issues/307 which was closed without action.

**Comment by Shubhangikh** [comment]
I am experiencing the same issue.

**Comment by jhy** [comment]
I was able to fetch this using jsoup 1.14.1 (using [try.jsoup](https://try.jsoup.org/~uqqpOrB_IMowIZblRDI-hQYQwoc)) without issue. I assume it's fixed with the new session and cookie handling that I added in this release. 

LMK!

**Comment by richardmorleysmith** [comment]
Hi @jhy,

I've encountered this error recently in version 1.18.3.

Here is what happens using try.jsoup:

<img width="552" alt="Image" src="https://github.com/user-attachments/assets/bbeb1422-f2cf-421c-9547-f2fa7d7941d0" />

Error:

```
java.io.IOException: Too many redirects occurred trying to load URL https://www.werk.nl/400.html
	at org.jsoup.helper.HttpConnection$Response.<init>(HttpConnection.java:1149) ~[jsoup-1.18.3.jar:1.18.3]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:869) ~[jsoup-1.18.3.jar:1.18.3]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:888) ~[jsoup-1.18.3.jar:1.18.3]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:888) ~[jsoup-1.18.3.jar:1.18.3]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:888) ~[jsoup-1.18.3.jar:1.18.3]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:888) ~[jsoup-1.18.3.jar:1.18.3]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:888) ~[jsoup-1.18.3.jar:1.18.3]
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:888) ~[jsoup-1.18.3.jar:1.18.3]
```

Any idea what might be going on?

**Comment by jhy** [comment]
@richardmorleysmith works for me currently: https://try.jsoup.org/~Q7O7KpI4QNrQTdsiODinujH-FCA (was very slow responding)

Maybe the site was previously serving a redirect loop? And it's stopped doing that?

For debugging, I would suggest running it under a mitm proxy and see what's different in the request vs a browser, or `curl -v` etc. If there's something that jsoup's missing, feel free to open a new issue.

**Comment by richardmorleysmith** [comment]
@jhy Thanks for getting back to me so quick.

I'm still getting the same unfortunately with https://www.werk.nl/werkzoekenden/

Let me do some more investigation and try to figure out exactly what's going on here and I'll get back to you if necessary. 👍
