### ISSUE TITLE
java.nio.charset.IllegalCharsetNameException: UTF-8,gb2312 

### ISSUE THREAD

**Issue by liangyangtao** [jhy/jsoup#434]
java.nio.charset.IllegalCharsetNameException: UTF-8,gb2312 
     at java.nio.charset.Charset.checkName(Unknown Source) 
     at java.nio.charset.Charset.lookup2(Unknown Source) 
     at java.nio.charset.Charset.lookup(Unknown Source) 
     at java.nio.charset.Charset.isSupported(Unknown Source) 
     at org.jsoup.helper.DataUtil.getCharsetFromContentType(DataUtil.java:154) 
     at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:465) 
     at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:410) 
     at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:164) 
     at org.jsoup.helper.HttpConnection.post(HttpConnection.java:159) 

我不会英语，读取中文编写URL，个别网页会报以上的错误

**Comment by jhy** [comment]
Sorry, I can't replicate this because that URL now throws a 404. But I changed jsoup recently to fallback to UTF-8 if the specified charset was not found. So should be fixed.

**Comment by liangyangtao** [comment]
http://caijing.nxnews.net/xyjj/

**Comment by liangyangtao** [comment]
hello，thanks you 
error  url :
http://caijing.nxnews.net/xyjj/        
java.nio.charset.IllegalCharsetNameException: gbk2312,UTF-8
	at java.nio.charset.Charset.checkName(Charset.java:320)
	at java.nio.charset.Charset.lookup2(Charset.java:489)
	at java.nio.charset.Charset.lookup(Charset.java:468)
	at java.nio.charset.Charset.isSupported(Charset.java:510)
	at org.jsoup.helper.DataUtil.getCharsetFromContentType(DataUtil.java:154)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:465)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:410)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:164)
	at org.jsoup.helper.HttpConnection.post(HttpConnection.java:159)

**Comment by jhy** [comment]
@liangyangtao thanks. I just checked that URL in jsoup and it works OK. Line 207 of DataUtil catches IllegalCharsetNameException, causing a UTF fallback.

I don't really understand what "charset=gbk2312,UTF-8" is supposed to mean, really. It can't be both, and if it's one, it can't be the other. They are mutually exclusive charsets.

**Comment by liangyangtao** [comment]
The following words are translated by translation software

After a long time, I suddenly thought of and the problem did not solve, today, look carefully the, found that this is not Jsoup wrong. Just because of the site's code of wrong, this should is "GBK", they wrote, "gbk2312" and judgment about and change to come over on OK.	
/**************************
                 Header heads[] = response.getAllHeaders();
				for (Header header : heads) {
					if (header.getValue().toLowerCase().contains("charset")) {
						Pattern pattern = Pattern
								.compile("charset=[^\\w]?([-\\w]+)");
						Matcher matcher = pattern.matcher(header.getValue());
						if (matcher.find()) {
							chartset = matcher.group(1);
						}
					}
				}

				if (chartset == null) {
					logger.info("通过Header 没有发现编码" + url);
					chartset = "utf-8";
				} else {
					logger.info("通过Header 发现编码" + url + "         " + chartset);
					if (chartset.equals("gbk2312")) {
						chartset = "gbk";
					}

				}
******************************/
